# Docker Compose configuration for multi-architecture support
# Supports both ARM64 and AMD64 architectures

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dalli-template-postgres
    platform: linux/amd64,linux/arm64
    environment:
      POSTGRES_DB: dalli_template
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dalli_template"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dalli-template-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/amd64}
        - TARGETOS=${TARGETOS:-linux}
        - TARGETARCH=${TARGETARCH:-amd64}
    container_name: dalli-template-backend
    platform: linux/amd64,linux/arm64
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/dalli_template
      - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
      - TARGETOS=${TARGETOS:-linux}
      - TARGETARCH=${TARGETARCH:-amd64}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - dalli-template-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/amd64}
        - TARGETOS=${TARGETOS:-linux}
        - TARGETARCH=${TARGETARCH:-amd64}
    container_name: dalli-template-frontend
    platform: linux/amd64,linux/arm64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000/api
      - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
      - TARGETOS=${TARGETOS:-linux}
      - TARGETARCH=${TARGETARCH:-amd64}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - dalli-template-network

volumes:
  postgres_data:

networks:
  dalli-template-network:
    driver: bridge
